---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(assertr)
library(stringr)
library(here)
```
read in tables
```{r}
candy_2015 <- read_excel(here("raw_data/boing-boing-candy-2015.xlsx"))
candy_2016 <- read_excel(here("raw_data/boing-boing-candy-2016.xlsx"))
candy_2017 <- read_excel(here("raw_data/boing-boing-candy-2017.xlsx"))
```

clean names
```{r}
candy_2015 <- clean_names(candy_2015)
candy_2016 <- clean_names(candy_2016)
candy_2017 <- clean_names(candy_2017)
```

look at names
```{r}
# candy_2015 %>%
#   names()
# 
# candy_2016 %>% 
#   names()
# 
# candy_2017 %>% 
#   names()
```


```{r}
candy_2016 %>% 
  distinct(how_old_are_you)
```


--------------------------------------------------------------------------------
# 2015
rename columns
```{r}
candy_2015 <- candy_2015 %>% 
  rename(boxo_raisins = box_o_raisins,
         hersheys_kisses = hershey_s_kissables,
         licorice_yes_black = licorice)
```


find the outliers for age
```{r}
# candy_2015 %>% 
#   arrange(how_old_are_you) %>% 
#   distinct(how_old_are_you) %>% 
#   pull()
```


change outlier ages where appropriate
```{r}
candy_2015_ages <- candy_2015 %>% 
  mutate(how_old_are_you = str_remove_all(how_old_are_you, "[0-9][0-9][0-9]"),
         how_old_are_you = str_remove_all(how_old_are_you, "3.14%"),
         how_old_are_you = str_replace(how_old_are_you, ">39", "39"),
         how_old_are_you = str_replace(how_old_are_you, "７１＋", "71"),
         how_old_are_you = str_replace(how_old_are_you, "Good Lord!  I'm 43!", "43"))
```

```{r}
# candy_2015_ages %>%
#   arrange(how_old_are_you) %>%
#   distinct(how_old_are_you) %>%
#   pull()
```


pivot longer
```{r}
candy_2015_longer <- candy_2015_ages %>% 
  pivot_longer(cols = c(butterfinger:york_peppermint_patties, sea_salt_flavored_stuff_probably_chocolate_since_this_is_the_it_flavor_of_the_year, necco_wafers),
               names_to = "candies",
               values_to = "rating")

candy_2015_longer
```


add year column
move new columns
select columns
rename columns
```{r}
candy_2015_clean <- candy_2015_longer %>% 
  mutate(year = 2015) %>% 
  relocate(c(candies:year), .after = timestamp) %>% 
  select(c(candies:are_you_going_actually_going_trick_or_treating_yourself)) %>% 
  rename(age = how_old_are_you,
         trick_or_treating = are_you_going_actually_going_trick_or_treating_yourself)
```



change age column to numeric
```{r}
candy_2015_clean <- candy_2015_clean %>% 
  mutate(age = str_extract(age, "^[0-9]+")) %>% 
  mutate(age = as.numeric(age))
```


filter ages
```{r}
candy_2015_clean <- candy_2015_clean %>% 
  filter(age > 0,
         age < 100)
```

add countries and gender column
```{r}
candy_2015_clean <- candy_2015_clean %>% 
  mutate(country = "",
         country = na_if(country, ""),
         gender = "",
         gender = na_if(gender, ""))
```

Look at outlying candies
```{r}
# candies_2015 <- candy_2015_clean %>%
#   arrange(candies) %>% 
#   distinct(candies) %>% 
#   pull()
```

```{r}
candy_2015_clean %>% 
  distinct(rating)
```

```{r}
candy_2015_clean %>% 
  distinct(trick_or_treating)
```

```{r}
candy_2015_clean %>% 
  distinct(age)
```



--------------------------------------------------------------------------------

# 2016

find the outliers for age
```{r}
# candy_2016 %>%
#   arrange(how_old_are_you) %>%
#   distinct(how_old_are_you) %>%
#   pull()
```


```{r}
candy_2016_ages <- candy_2016 %>% 
  mutate(how_old_are_you = str_remove_all(how_old_are_you, "[0-9][0-9][0-9]"),
         how_old_are_you = str_replace(how_old_are_you, "49 11/12ths", "49"),
         how_old_are_you = str_replace(how_old_are_you, "Fifty.  Nine.  Ish.", "59"))
```
```{r}
country_names <- candy_2016_ages %>%
  select(which_country_do_you_live_in) %>%
  filter(!is.na(which_country_do_you_live_in)) %>% 
  mutate(country_detect = str_detect(which_country_do_you_live_in, "(^(?i)U+(?i)[ns]+ *[:punct:]*(?i)s* *[:punct:]*(?i)a* *[:punct:]*)+"))

country_names %>% 
  filter(country_detect == TRUE)
```



```{r}
candy_2016_longer <- candy_2016_ages %>% 
  pivot_longer(cols = c(x100_grand_bar:york_peppermint_patties),
               names_to = "candies",
               values_to = "rating")

candy_2016_longer
```

```{r}
candy_2016_clean <- candy_2016_longer %>% 
  mutate(year = 2016) %>% 
  relocate(c(candies:year), .after = timestamp) %>% 
  select(c(candies:which_country_do_you_live_in)) %>% 
  rename(age = how_old_are_you,
         trick_or_treating = are_you_going_actually_going_trick_or_treating_yourself,
         gender = your_gender,
         country = which_country_do_you_live_in)
```


```{r}
candy_2016_clean <- candy_2016_clean %>% 
    relocate(age, .after = year)

candy_2016_clean <- candy_2016_clean %>% 
  relocate(gender, .after = country)
```


```{r}
candy_2016_clean <- candy_2016_clean %>% 
  mutate(age = str_extract(age, "^[0-9]+")) %>% 
  mutate(age = as.numeric(age))
```

```{r}
candy_2016_clean <- candy_2016_clean %>% 
  filter(age > 0,
         age < 100)
```

```{r}
candy_2016_clean <- candy_2016_clean %>% 
  mutate(country = str_to_title(country))
```


Find outlying candies
```{r}
# candies_2016 <- candy_2016_clean %>% 
#   arrange(candies) %>% 
#   distinct(candies) %>% 
#   pull()
```

```{r}
candy_2016_clean %>% 
  distinct(rating)
```

```{r}
candy_2016_clean %>% 
  distinct(gender)
```

```{r}
candy_2016_clean %>% 
  distinct(trick_or_treating)
```


--------------------------------------------------------------------------------
# 2017

```{r}
candy_2017 <- candy_2017 %>% 
  rename_with(~ gsub("^q[0-9]_", "", .x))

candy_2017 <- candy_2017 %>% 
  rename_with(~str_replace(., "^", "x"), .cols = starts_with("100"))

candy_2017 <- candy_2017 %>% 
  rename(anonymous_brown_globs_that_come_in_black_and_orange_wrappers = anonymous_brown_globs_that_come_in_black_and_orange_wrappers_a_k_a_mary_janes)
```


find the outliers for age
```{r}
candy_2017 %>%
  arrange(age) %>%
  distinct(age) %>%
  pull()
```


```{r}
candy_2017_ages <- candy_2017 %>% 
  mutate(age = str_remove_all(age, "[0-9][0-9][0-9]"),
         age = str_replace(age, "45-55", "50"),
         age = str_replace(age, "24-50", "37"),
         age = str_replace(age, "sixty-nine", "69"))
```


```{r}
candy_2017_longer <- candy_2017_ages %>% 
  pivot_longer(cols = c(x100_grand_bar:york_peppermint_patties),
               names_to = "candies",
               values_to = "rating")

candy_2017_longer
```

```{r}
candy_2017_clean <- candy_2017_longer %>% 
  mutate(year = 2017) %>% 
  relocate(c(candies:year), .after = internal_id) %>% 
  select(c(candies:country)) %>% 
  rename(trick_or_treating = going_out)
```


```{r}
candy_2017_clean <- candy_2017_clean %>% 
  relocate(age, .after = year)

candy_2017_clean <- candy_2017_clean %>% 
  relocate(gender, .after = country)
```


```{r}
candy_2017_clean <- candy_2017_clean %>% 
  mutate(age = str_extract(age, "^[0-9]+")) %>% 
  mutate(age = as.numeric(age))
```

```{r}
candy_2017_clean <- candy_2017_clean %>% 
  filter(age > 0,
         age < 100)
```


```{r}
candies_2017 <- candy_2017_clean %>%
  arrange(candies) %>% 
  distinct(candies) %>% 
  pull()
```



--------------------------------------------------------------------------------
# Find outliers in candies
```{r}
# Candies in 2015 that are not in 2016
candies_2015[!(candies_2015 %in% candies_2016)]
```

```{r}
# Candies in 2015 that are not in 2017
candies_2015[!(candies_2015 %in% candies_2017)]
```


```{r}
# Candies in 2016 that are not in 2015
candies_2016[!(candies_2016 %in% candies_2015)]
```

```{r}
# Candies in 2016 that are not in 2017
candies_2016[!(candies_2016 %in% candies_2017)]
```



```{r}
# Candies in 2017 that are not in 2015
candies_2017[!(candies_2017 %in% candies_2015)]
```

```{r}
# Candies in 2017 that are not in 2016
candies_2017[!(candies_2017 %in% candies_2016)]
```

--------------------------------------------------------------------------------
# Join tables by binding rows

```{r}
candy <- bind_rows(candy_2015_clean, candy_2016_clean, candy_2017_clean)

candy
```

```{r}
candy <- candy %>% 
  mutate(country = str_to_title(country))
```

--------------------------------------------------------------------------------
# Sort countries

```{r}
candy %>% 
  distinct(country)
```

```{r}
# candy_country_sorted <- candy %>%
#   mutate(country = str_replace_all(country, "(^(?i)U+(?i)[ns]+ *[:punct:]*(?i)s* *[:punct:]*(?i)a* *[:punct:]*)+", "USA"))
         # country = str_replace_all(country, "^U?[a-z]* S?[a-z]* O?[a-z]* A?[a-z]*", "USA"),
         # country = str_replace_all(country, "^U{1}[:punct:](s[:punct:])*(a[:punct:])*", "USA"),
         # country = str_replace_all(country, "^U[a-z]+ S[a-z]+", "USA"),
         # country = str_replace_all(country, "Murica", "USA"),
         # country = str_replace_all(country, "^U{1}S+A*[:punct:]*", "USA"),
         # country = str_replace_all(country, "(?i)America", "USA"),
         # country = str_replace_all(country, "([a-z]*[:punct:]*)* *(?i)usa *([a-z]*[:punct:]*)*", "USA"),
         # country = str_replace_all(country, "USAUSA", "USA"),
         # country = str_replace_all(country, "The Best One - Usa", "USA"),
         # country = str_replace_all(country, "The Best One USA", "USA"),
         # country = str_replace_all(country, "United States OUSA", "USA"),
         # country = str_replace_all(country, "USA Usa! Usa!", "USA"),
         # country = str_replace_all(country, "The Yoo Ess Of Aaayyyyyy", "USA"),
         # country = str_replace_all(country, "God's Country", "USA"),
         # country = str_replace_all(country, "God's Country", "USA"),
         # country = str_replace_all(country, "(USA Usa)+!*", "USA"),
         # country = str_replace_all(country, "Merica", "USA"),
         # country = str_replace_all(country, "United States Of USA", "USA"),
         # country = str_replace_all(country, "us+a+", "USA"),
         # country = str_replace_all(country, "united states", "USA"),
         # country = str_replace_all(country, "^us$", "USA"),
         # country = str_replace_all(country, "United staes", "USA"),
         # country = str_replace_all(country, "United states", "USA"),
         # country = str_replace_all(country, "u.s.a.", "USA"),
         # country = str_replace_all(country, "USAUSA", "USA"),
         # country = str_replace_all(country, "USAS.A.", "USA"),
         # country = str_replace_all(country, "unhinged states", "USA"),
         # country = str_replace_all(country, "USA Of A", "USA"),
         # country = str_replace_all(country, "The United States", "USA"),
         # country = str_replace_all(country, "North Carolina", "USA"),
         # country = str_replace_all(country, "U S", "USA"),
         # country = str_replace_all(country, "USAk.", "USA"),
         # country = str_replace_all(country, "The USA", "USA"),
         # country = str_replace_all(country, "USA Hard To Tell Anymore..", "USA"),
         # country = str_replace_all(country, "Pittsburgh", "USA"),
         # country = str_replace_all(country, "New York", "USA"),
         # country = str_replace_all(country, "Trumpistan", "USA"),
         # country = str_replace_all(country, "California", "USA"),
         # country = str_replace_all(country, "USA OUSA", "USA"),
         # country = str_replace_all(country, "I Pretend To Be From Canada, But I Am Really From The United States.", "USA"),
         # country = str_replace_all(country, "I Pretend To Be From Canada, But I Am Really From USA.", "USA"),
         # country = str_replace_all(country, "New Jersey", "USA"),
         # country = str_replace_all(country, "Murrika", "USA"),
         # country = str_replace_all(country, "Alaska", "USA"),
         # country = str_replace_all(country, "N. USA", "USA"),
         # country = str_replace_all(country, "U S A", "USA"),
         # country = str_replace_all(country, "USA A", "USA"),
         # country = str_replace_all(country, "USA To Tell Anymore..", "USA"),
         # country = str_replace_all(country, "'USA", "USA"),
         # country = str_replace_all(country, "NUSA", "USA"),
         # country = str_replace_all(country, "Uk", "UK"),
         # country = str_replace_all(country, "United Kingdom", "UK"),
         # country = str_replace_all(country, "United Kindom", "UK"),
         # country = str_replace_all(country, "England", "UK"),
         # country = str_replace_all(country, "Scotland", "UK"),
         # country = str_replace_all(country, "Endland", "UK"),
         # country = str_replace_all(country, "^Can$", "Canada"),
         # country = str_replace_all(country, "Canae", "Canada"),
         # country = str_replace_all(country, "Canada`", "Canada"),
         # country = str_replace_all(country, "España", "Spain"),
         # country = str_replace_all(country, "The Netherlands", "Netherlands"))
```

other country outliers
```{r}
country_outliers = c("A tropical island south of the equator", "Ud", "Atlantis",
                 "Canae", "cascadia ", "Cascadia", "Denial", "Earth", "1", 
                 "god's country", "I Don't Know Anymore", "insanity lately", 
                 "There Isn't One For Old Men", "Soviet Canuckistan", "Narnia", "Neverland",
                 "one of the best ones", "See above", "Somewhere", "subscribe to dm4uz3 on youtube",
                 "The Republic Of Cascadia", "this one", "Eua", "Europe", "God's Country")
```


```{r}
states <- c("North Carolina", "Pittsburgh", "New York", "California", "New Jersey", "Alaska")
uk <- c("England", "Scotland", "Endland")
```


```{r}
candy_country_sorted <- candy %>% 
  mutate(country = case_when(
    str_detect(country,"((?i)[a-z]* *[:punct:])*((?i)^u+ *[:punct:]*(?i)[ns]+ *[:punct:]*(?i)s* *[:punct:]*(?i)a* *[:punct:]*)+((?i)[a-z]* *[:punct:])*") ~ "USA",
    str_detect(country, "(?i)a+mer") ~ "USA",
    str_detect(country, "(?i)t+[a-z]* *(?i)u+[a-z]* *(?i)s+[a-z]* *(?i)o*[a-z]* *(?i)a*[a-z]*") ~ "USA",
    str_detect(country, " +U+[sa]*") ~ "USA",
    str_detect(country, "T+[a-z]* Y+[a-z]* E+[a-z]* O+[a-z]* A+[a-z]*") ~ "USA",
    str_detect(country, "[:punct:]*M+[ue]+[r]+") ~ "USA",
    country %in% states ~ "USA",
    str_detect(country, "^(?i)u+[:punct:]*(?i)k+") ~ "UK",
    country %in% uk ~ "UK",
    str_detect(country, "(^(?i)can)+[a-z]*[:punct:]*") ~ "Canada",
    str_detect(country, "ñ+") ~ "Spain",
    str_detect(country, "The N+") ~ "Netherlands",
    TRUE ~ country
  ))
```

```{r}
candy_country_sorted <- candy_country_sorted %>% 
  mutate(country = if_else(country %in% country_outliers, NA_character_, country))
```

```{r}
candy_country_sorted %>% 
  distinct(country)
```













```{r}

```

